### PR TITLE
feat: cost configuration and calculations for stats page

### PR DESCRIPTION
**Pull request by gruckion**
- Adds support for calculating the cost for input and output tokens with configuration for the pricing of OpenAI and Anthropic models.
- Also refactors and types the Prisma where clause and only adds if conditions are provided.
- Switch to `for(const x of y)` instead of `x.forEach`. forEach creates a new callback for each iteration and doesn't work with break/continue as well as not working with async operations.

### CODE REVIEW

**Comment by HamedMP** [comment]
This looks awesome @gruckion 🔥

**Comment by HamedMP** [comment]
I wonder why I am still seeing $0
image

Tried logging the `costData` but I can't be fully sure of the numbers, not all models that have a cost !=0 have been used e.g. `babbage`. 

image

**Comment by gruckion** [comment]
> I wonder why I am still seeing $0 image
> 
> Tried logging the `costData` but I can't be fully sure of the numbers, not all models that have a cost !=0 have been used e.g. `babbage`.
> 
> image

What is the name of your model. The model name key is the important property. Will also need to add additional config to cover the new models you've introduced.

We can run into an issue, since the user can freely put the model name I can put `OpenAI gpt 3-5` or any other combination. We will need to have this locked down to a selector instead of free form text / templates.

**Comment by HamedMP** [comment]
Hmm, in the latest version the model name is chosen from a dropdown, can we unify them together?

**Comment by gruckion** [comment]
> Hmm, in the latest version the model name is chosen from a dropdown, can we unify them together?

Perfect, I will align with this.

**Comment by gruckion** [comment]
Updated:

1. Refactored to a single source of truth for the model / provider configuration.

```ts
import { getModelConfigurations } from "@/lib/model-config";
```

2. Refactored the `actions.ts` for the `getConfigurationCost()` to make use of this single source of truth object.
3. Refactored the configurations page to make use of the single source of truth.


Also left a TODO comment, we can improve the UX with a toaster.

```
  // TODO: Implement proper handling when turning off a default configuration
  // - Prevent turning off the last default configuration
  // - Show a toast message explaining why the action is not allowed
  // - Implement logic to ensure at least one configuration is always set as default

{/* TODO: Add an "Actions" column for edit functionality */}
```

**Comment by HamedMP** [comment]
Oh beautiful,  testing it now 😍

**Pull request merged**
