### PR TITLE
feat: setup t3-oss-env and refactor ai model client

### PR DESCRIPTION
**Pull request by gruckion**
- Setup t3-oss env for type safe `.env`.
- Refactored the ai model provider code into its own function `getAIModelClient`

### CODE REVIEW

**Comment by HamedMP** [comment]
Really good, just need that `.optional()` in the end of all API key variables and it's good to 🚀

**Comment by gruckion** [comment]
Well spotted. I also addressed the warnings about the prisma `global` in this PR.

```
Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.ts(7017)
```

**Comment by gruckion** [comment]
NOT tested yet!

**Comment by gruckion** [comment]
Tested all looks fine, please remove label and merge.

**Pull request merged**
